// frontend/src/components/character/RelationshipGraph.tsx
'use client';

import { useCallback, useMemo } from 'react';
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  Position,
  type Node,
  type Edge,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useScriptStore } from '@/stores/script-store';
import { roleLabel } from '@/lib/utils';
import type { Character } from '@/types/character';

// ---- Relationship color mapping ----
const RELATION_COLORS: Record<string, { stroke: string; glow: string }> = {
  家人:    { stroke: 'oklch(0.65 0.18 40 / 0.8)',  glow: 'oklch(0.65 0.18 40 / 0.3)' },   // warm orange
  亲戚:    { stroke: 'oklch(0.65 0.18 40 / 0.7)',  glow: 'oklch(0.65 0.18 40 / 0.25)' },
  恋人:    { stroke: 'oklch(0.58 0.2 0 / 0.8)',    glow: 'oklch(0.58 0.2 0 / 0.3)' },     // rose/pink
  情侣:    { stroke: 'oklch(0.58 0.2 0 / 0.8)',    glow: 'oklch(0.58 0.2 0 / 0.3)' },
  夫妻:    { stroke: 'oklch(0.58 0.2 0 / 0.85)',   glow: 'oklch(0.58 0.2 0 / 0.35)' },
  朋友:    { stroke: 'oklch(0.65 0.14 140 / 0.8)',  glow: 'oklch(0.65 0.14 140 / 0.3)' },  // green
  好友:    { stroke: 'oklch(0.65 0.14 140 / 0.85)', glow: 'oklch(0.65 0.14 140 / 0.35)' },
  盟友:    { stroke: 'oklch(0.65 0.14 160 / 0.8)',  glow: 'oklch(0.65 0.14 160 / 0.3)' },  // teal
  敌人:    { stroke: 'oklch(0.55 0.2 20 / 0.85)',   glow: 'oklch(0.55 0.2 20 / 0.35)' },   // red
  对手:    { stroke: 'oklch(0.55 0.2 20 / 0.75)',   glow: 'oklch(0.55 0.2 20 / 0.3)' },
  师徒:    { stroke: 'oklch(0.62 0.15 260 / 0.8)',  glow: 'oklch(0.62 0.15 260 / 0.3)' },  // blue-purple
  师傅:    { stroke: 'oklch(0.62 0.15 260 / 0.85)', glow: 'oklch(0.62 0.15 260 / 0.35)' },
  徒弟:    { stroke: 'oklch(0.62 0.15 260 / 0.75)', glow: 'oklch(0.62 0.15 260 / 0.3)' },
  师生:    { stroke: 'oklch(0.62 0.15 260 / 0.8)',  glow: 'oklch(0.62 0.15 260 / 0.3)' },
  上下级:  { stroke: 'oklch(0.55 0.08 270 / 0.8)',  glow: 'oklch(0.55 0.08 270 / 0.25)' }, // gray-blue
  同事:    { stroke: 'oklch(0.55 0.08 270 / 0.75)', glow: 'oklch(0.55 0.08 270 / 0.25)' },
  相识:    { stroke: 'oklch(0.5 0.03 280 / 0.6)',   glow: 'oklch(0.5 0.03 280 / 0.2)' },   // muted gray
  邻居:    { stroke: 'oklch(0.5 0.03 280 / 0.6)',   glow: 'oklch(0.5 0.03 280 / 0.2)' },
};

function getRelationColor(relation: string): { stroke: string; glow: string } {
  // Try exact match first
  if (RELATION_COLORS[relation]) return RELATION_COLORS[relation];
  // Try partial match
  for (const [key, color] of Object.entries(RELATION_COLORS)) {
    if (relation.includes(key) || key.includes(relation)) return color;
  }
  // Default teal
  return { stroke: 'oklch(0.72 0.14 185 / 0.6)', glow: 'oklch(0.72 0.14 185 / 0.2)' };
}

// ---- Layout helpers ----
function buildLayout(characters: Character[]) {
  const nodes: Node[] = [];
  const edges: Edge[] = [];
  const edgeSet = new Set<string>();

  // Position characters in a circle
  const centerX = 400;
  const centerY = 300;
  const radius = Math.min(240, characters.length * 60);
  const angleStep = (2 * Math.PI) / Math.max(1, characters.length);

  characters.forEach((char, i) => {
    const angle = i * angleStep - Math.PI / 2;
    const x = centerX + radius * Math.cos(angle);
    const y = centerY + radius * Math.sin(angle);

    const isProtagonist = char.roleType === 'PROTAGONIST';
    const isAntagonist = char.roleType === 'ANTAGONIST';

    nodes.push({
      id: String(char.id),
      type: 'default',
      position: { x, y },
      data: {
        label: char.canonicalName,
        aliases: char.aliases?.join(', ') || '',
        role: roleLabel(char.roleType),
        appearanceCount: char.appearanceCount,
        gender: char.gender,
        isProtagonist,
        isAntagonist,
      },
      style: {
        background: isProtagonist
          ? 'oklch(0.72 0.14 185 / 0.15)'
          : isAntagonist
          ? 'oklch(0.55 0.2 20 / 0.15)'
          : 'oklch(0.9 0.005 250 / 0.08)',
        border: isProtagonist
          ? '2px solid oklch(0.72 0.14 185 / 0.6)'
          : isAntagonist
          ? '2px solid oklch(0.55 0.2 20 / 0.6)'
          : '1px solid oklch(0.9 0.005 250 / 0.15)',
        borderRadius: '12px',
        padding: '10px 16px',
        color: 'oklch(0.95 0.005 250)',
        fontSize: '13px',
        fontWeight: 600,
        width: 'auto',
        minWidth: 120,
      },
      sourcePosition: Position.Right,
      targetPosition: Position.Left,
    });
  });

  // Build edges from relationships
  characters.forEach((char) => {
    char.relationships?.forEach((rel) => {
      const target = characters.find(
        (c) => c.canonicalName === rel.target || c.aliases?.includes(rel.target)
      );
      if (target) {
        const edgeKey = [char.id, target.id].sort().join('-');
        if (!edgeSet.has(edgeKey)) {
          edgeSet.add(edgeKey);
          const colors = getRelationColor(rel.relation);
          edges.push({
            id: `e${char.id}-${target.id}`,
            source: String(char.id),
            target: String(target.id),
            label: rel.relation,
            style: {
              stroke: colors.stroke,
              strokeWidth: 2,
            },
            labelStyle: {
              fill: 'oklch(0.95 0.005 250)',
              fontSize: 11,
              fontWeight: 600,
            },
            labelBgStyle: {
              fill: 'oklch(0.15 0.01 250 / 0.9)',
              rx: 4,
              ry: 4,
            },
            labelBgPadding: [6, 3] as [number, number],
            labelBgBorderRadius: 4,
            animated: true,
          });
        }
      }
    });
  });

  return { nodes, edges };
}

// ---- Custom node ----
interface CharacterNodeData {
  label: string;
  aliases: string;
  role: string;
  appearanceCount: number;
  gender?: string;
  isProtagonist?: boolean;
  isAntagonist?: boolean;
}

function CharacterNode({ data }: { data: CharacterNodeData }) {
  const genderLabel = data.gender === 'MALE' ? '♂' : data.gender === 'FEMALE' ? '♀' : '';
  return (
    <div className="relative">
      <div className="text-xs opacity-60 mb-0.5">{data.role}</div>
      <div className="font-semibold text-sm">
        {data.label}
        {genderLabel && (
          <span className={`ml-1 text-xs ${data.gender === 'MALE' ? 'text-blue-400' : 'text-pink-400'}`}>
            {genderLabel}
          </span>
        )}
      </div>
      {data.aliases && (
        <div className="text-[10px] opacity-40 mt-0.5">{data.aliases}</div>
      )}
      <div className="text-[10px] opacity-50 mt-1">
        出场 {data.appearanceCount} 次
      </div>
    </div>
  );
}

const nodeTypes = { default: CharacterNode };

// ---- Component ----
export function RelationshipGraph() {
  const { script, selectCharacter } = useScriptStore();
  const characters = script?.characters ?? [];

  const { nodes: initialNodes, edges: initialEdges } = useMemo(
    () => buildLayout(characters),
    [characters]
  );

  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onNodeClick = useCallback(
    (_event: React.MouseEvent, node: Node) => {
      selectCharacter(Number(node.id));
    },
    [selectCharacter]
  );

  if (characters.length === 0) return null;

  return (
    <div className="rounded-xl border border-white/5 bg-white/[0.02] overflow-hidden">
      <div className="px-4 py-3 border-b border-white/5">
        <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          角色关系图谱
        </h3>
      </div>
      <div style={{ height: 500, width: '100%' }}>
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onNodeClick={onNodeClick}
          nodeTypes={nodeTypes}
          fitView
          fitViewOptions={{ padding: 0.3 }}
          minZoom={0.3}
          maxZoom={2}
          defaultViewport={{ x: 0, y: 0, zoom: 1 }}
          proOptions={{ hideAttribution: true }}
        >
          <Background
            color="oklch(1 0 0 / 0.06)"
            gap={20}
            size={0.5}
          />
          <Controls
            className="!bg-oklch(0.17 0.012 250 / 0.9) !border !border-white/10 !rounded-lg"
            style={{
              // @ts-expect-error custom css vars
              '--xy-controls-button-background-color': 'oklch(0.22 0.012 255 / 0.8)',
              '--xy-controls-button-background-color-hover': 'oklch(0.28 0.012 255 / 0.8)',
              '--xy-controls-button-color': 'oklch(0.9 0.005 250)',
              '--xy-controls-button-color-hover': 'oklch(0.95 0.005 250)',
              '--xy-controls-button-border-color': 'oklch(1 0 0 / 0.1)',
            }}
          />
          <MiniMap
            className="!bg-oklch(0.17 0.012 250 / 0.9) !border !border-white/10 !rounded-lg"
            maskColor="oklch(0.13 0.015 250 / 0.7)"
            nodeColor={(node) => {
              const d = node.data as unknown as CharacterNodeData | undefined;
              return d?.isProtagonist
                ? 'oklch(0.72 0.14 185)'
                : d?.isAntagonist
                ? 'oklch(0.55 0.2 20)'
                : 'oklch(0.62 0.02 250)';
            }}
            pannable
            zoomable
          />
        </ReactFlow>
      </div>
    </div>
  );
}

// frontend-vue/src/components/character/RelationshipGraph.vue
<template>
  <div class="rel-graph" v-if="characters.length > 0">
    <svg :viewBox="`0 0 ${svgSize} ${svgSize}`" class="rel-svg">
      <!-- Edges -->
      <g v-for="(edge, i) in edges" :key="'edge-' + i">
        <line
          :x1="edge.x1" :y1="edge.y1"
          :x2="edge.x2" :y2="edge.y2"
          :stroke="edge.color"
          :stroke-width="1.5"
          :stroke-dasharray="edge.isDashed ? '6,3' : 'none'"
          opacity="0.4"
        />
        <text
          v-if="edge.label"
          :x="(edge.x1 + edge.x2) / 2"
          :y="(edge.y1 + edge.y2) / 2 - 4"
          text-anchor="middle"
          :fill="edge.color"
          font-size="10"
          opacity="0.7"
        >{{ edge.label }}</text>
      </g>

      <!-- Nodes -->
      <g
        v-for="node in nodes"
        :key="'node-' + node.id"
        class="graph-node"
        :class="{ 'graph-node--active': selectedId === node.id }"
        @click="$emit('select', node.id)"
      >
        <!-- Glow ring for active -->
        <circle
          v-if="selectedId === node.id"
          :cx="node.x" :cy="node.y" r="28"
          fill="none"
          :stroke="node.glowColor"
          stroke-width="1"
          opacity="0.3"
        >
          <animate attributeName="r" from="28" to="34" dur="2s" repeatCount="indefinite"/>
          <animate attributeName="opacity" from="0.3" to="0" dur="2s" repeatCount="indefinite"/>
        </circle>

        <!-- Node circle -->
        <circle
          :cx="node.x" :cy="node.y" r="22"
          :fill="node.bgColor"
          :stroke="node.borderColor"
          stroke-width="1.5"
        />
        <!-- Role dot -->
        <circle
          :cx="node.x - 8" :cy="node.y - 10" r="4"
          :fill="node.dotColor"
        />
        <!-- Name -->
        <text
          :x="node.x" :y="node.y + 4"
          text-anchor="middle"
          fill="var(--text-primary)"
          font-size="11"
          font-weight="500"
        >{{ node.name.length > 3 ? node.name.slice(0, 3) + '…' : node.name }}</text>
        <!-- Role label below -->
        <text
          :x="node.x" :y="node.y + 32"
          text-anchor="middle"
          fill="var(--text-muted)"
          font-size="9"
          opacity="0.6"
        >{{ node.roleLabel }}</text>
      </g>
    </svg>

    <!-- Legend -->
    <div class="graph-legend">
      <span v-for="rel in legendItems" :key="rel.label" class="legend-item">
        <span class="legend-dot" :style="{ background: rel.color }"></span>
        {{ rel.label }}
      </span>
    </div>
  </div>
  <div v-else class="graph-empty">
    <span>📊</span>
    <p>没有足够的角色数据来生成关系图</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { roleLabel } from '@/lib/utils'
import type { Character } from '@/types/character'

const props = defineProps<{
  characters: Character[]
  selectedId?: number | null
}>()

defineEmits<{
  select: [id: number]
}>()

const svgSize = 500
const centerX = svgSize / 2
const centerY = svgSize / 2
const radius = 180

interface GraphNode {
  id: number
  name: string
  x: number
  y: number
  bgColor: string
  borderColor: string
  glowColor: string
  dotColor: string
  roleLabel: string
}

interface GraphEdge {
  x1: number; y1: number
  x2: number; y2: number
  color: string
  label: string
  isDashed: boolean
}

const roleColors: Record<string, { bg: string; border: string; glow: string; dot: string }> = {
  PROTAGONIST: { bg: 'rgba(194, 59, 34, 0.15)', border: 'rgba(194, 59, 34, 0.4)', glow: '#C23B22', dot: '#C23B22' },
  ANTAGONIST: { bg: 'rgba(155, 89, 182, 0.15)', border: 'rgba(155, 89, 182, 0.4)', glow: '#9b59b6', dot: '#9b59b6' },
  DEUTERAGONIST: { bg: 'rgba(212, 168, 83, 0.15)', border: 'rgba(212, 168, 83, 0.4)', glow: '#D4A853', dot: '#D4A853' },
  SUPPORTING: { bg: 'rgba(61, 184, 176, 0.15)', border: 'rgba(61, 184, 176, 0.4)', glow: '#3DB8B0', dot: '#3DB8B0' },
  MINOR: { bg: 'rgba(255, 255, 255, 0.05)', border: 'rgba(255, 255, 255, 0.15)', glow: '#787066', dot: '#787066' },
}

const relColorMap: Record<string, string> = {
  '恋人': '#f472b6', '夫妻': '#f472b6', '情人': '#f472b6', 'love': '#f472b6',
  '仇敌': '#C23B22', '敌人': '#C23B22', '对手': '#C23B22', 'enemy': '#C23B22',
  '师徒': '#3DB8B0', '老师': '#3DB8B0', '学生': '#3DB8B0', 'master': '#3DB8B0',
  '朋友': '#22c55e', '好友': '#22c55e', 'friend': '#22c55e',
  '家人': '#f97316', '父亲': '#f97316', '母亲': '#f97316', '兄弟': '#f97316', '姐妹': '#f97316', 'family': '#f97316',
  '同门': '#a78bfa', '同事': '#a78bfa',
}

function getRelColor(relation: string): string {
  for (const [key, color] of Object.entries(relColorMap)) {
    if (relation.includes(key)) return color
  }
  return '#787066'
}

const nodes = computed<GraphNode[]>(() => {
  const chars = props.characters
  return chars.map((c, i) => {
    const angle = (2 * Math.PI * i) / chars.length - Math.PI / 2
    const x = centerX + radius * Math.cos(angle)
    const y = centerY + radius * Math.sin(angle)
    const colors = roleColors[c.roleType] ?? roleColors.MINOR
    return {
      id: c.id,
      name: c.canonicalName,
      x, y,
      bgColor: colors.bg,
      borderColor: colors.border,
      glowColor: colors.glow,
      dotColor: colors.dot,
      roleLabel: roleLabel(c.roleType),
    }
  })
})

const edges = computed<GraphEdge[]>(() => {
  const nodeMap = new Map(nodes.value.map((n) => [n.id, n]))
  const result: GraphEdge[] = []
  const seen = new Set<string>()

  for (const char of props.characters) {
    const source = nodeMap.get(char.id)
    if (!source) continue
    for (const rel of char.relationships) {
      const target = props.characters.find((c) =>
        c.canonicalName === rel.target || c.aliases.includes(rel.target)
      )
      if (!target) continue
      const targetNode = nodeMap.get(target.id)
      if (!targetNode) continue

      const key = [Math.min(char.id, target.id), Math.max(char.id, target.id)].join('-')
      if (seen.has(key)) continue
      seen.add(key)

      result.push({
        x1: source.x, y1: source.y,
        x2: targetNode.x, y2: targetNode.y,
        color: getRelColor(rel.relation),
        label: rel.relation,
        isDashed: rel.relation === '旧识' || rel.relation === 'neutral',
      })
    }
  }

  return result
})

const legendItems = computed(() => [
  { label: '恋人/夫妻', color: '#f472b6' },
  { label: '仇敌/对手', color: '#C23B22' },
  { label: '师徒', color: '#3DB8B0' },
  { label: '朋友', color: '#22c55e' },
  { label: '家人', color: '#f97316' },
])
</script>

<style scoped>
.rel-graph {
  background: var(--glass-bg);
  backdrop-filter: blur(12px);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-lg);
  padding: 16px;
}

.rel-svg {
  width: 100%;
  height: auto;
}

.graph-node {
  cursor: pointer;
  transition: opacity 0.2s;
}

.graph-node:hover {
  opacity: 0.8;
}

.graph-node--active circle:first-of-type {
  opacity: 1;
}

.graph-legend {
  display: flex;
  justify-content: center;
  gap: 16px;
  margin-top: 12px;
  flex-wrap: wrap;
}

.legend-item {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 10px;
  color: var(--text-muted);
}

.legend-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
}

.graph-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 32px;
  color: var(--text-muted);
  font-size: 13px;
}
</style>
