// frontend-vue/src/components/script/ActionBlock.vue
<template>
  <div class="action-block" :class="{ 'action-block--editing': isEditing }">
    <!-- Edit Mode -->
    <div v-if="isEditing" class="action-edit">
      <div class="edit-header">
        <span class="action-type-tag">{{ actionTypeLabel(action.actionType) }}</span>
        <span class="edit-indicator">编辑模式</span>
      </div>

      <textarea
        ref="textareaRef"
        class="edit-textarea"
        v-model="localDescription"
        rows="3"
        placeholder="输入动作描述..."
        @keydown="handleKeydown"
      ></textarea>

      <!-- Actions (hidden when parent toolbar provides them) -->
      <div v-if="!hideActions" class="edit-footer">
        <label class="duration-field">
          <span>时长 (ms)</span>
          <input
            class="duration-input"
            v-model="localDurationMs"
            placeholder="auto"
          />
        </label>
        <span class="flex-1"></span>
        <button class="btn-cancel" @click="handleCancel">取消</button>
        <button class="btn-save" @click="handleSave">保存</button>
      </div>
      <p v-if="!hideActions" class="shortcut-hint">Ctrl+Enter 保存 · Esc 取消</p>
    </div>

    <!-- View Mode -->
    <div v-else class="action-view">
      <span class="action-type-tag">{{ actionTypeLabel(action.actionType) }}</span>
      <span class="action-desc">{{ action.description }}</span>
      <span v-if="action.durationMs" class="action-duration">
        ~{{ (action.durationMs / 1000).toFixed(1) }}s
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, useTemplateRef, onMounted, getCurrentInstance } from 'vue'
import { useScriptStore } from '@/stores/script'
import { toast } from '@/stores/toast'
import type { Action } from '@/types/script'

const props = defineProps<{
  action: Action
  editing?: boolean
  hideActions?: boolean
}>()

const emit = defineEmits<{
  'edit-state-change': [editing: boolean]
  'register-actions': [actions: { save: () => void; cancel: () => void } | null]
}>()

const store = useScriptStore()
const internalEditing = ref(false)
const localDescription = ref(props.action.description)
const localDurationMs = ref(props.action.durationMs?.toString() ?? '')
const textareaRef = useTemplateRef<HTMLTextAreaElement>('textareaRef')

const isEditing = computed(() =>
  props.editing !== undefined ? props.editing : internalEditing.value
)

// Sync when entering edit mode
watch(isEditing, (val) => {
  if (val) {
    localDescription.value = props.action.description
    localDurationMs.value = props.action.durationMs?.toString() ?? ''
  }
  // Focus textarea
  if (val) {
    setTimeout(() => {
      textareaRef.value?.focus()
      textareaRef.value?.select()
    }, 50)
  }
})

function actionTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    ACTION: '动作',
    REACTION: '反应',
    BEAT: '节拍',
    BUSINESS: '调度',
  }
  return labels[type] ?? type
}

function handleSave() {
  const trimmed = localDescription.value.trim()
  if (!trimmed) {
    toast.warning('请填写动作内容')
    return
  }

  const script = store.script
  const scene = script?.scenes.find((s) => s.id === props.action.sceneId)
  if (!scene) return

  const updatedActions = scene.actions.map((a) =>
    a.id === props.action.id
      ? {
          ...a,
          description: trimmed,
          durationMs: localDurationMs.value ? parseInt(localDurationMs.value, 10) || undefined : undefined,
        }
      : a
  )
  store.updateScene(props.action.sceneId, {
    actions: updatedActions as unknown as typeof scene.actions,
  } as Partial<typeof scene>)

  internalEditing.value = false
  emit('edit-state-change', false)
  toast.success('💾 段落已更新')
}

function handleCancel() {
  localDescription.value = props.action.description
  localDurationMs.value = props.action.durationMs?.toString() ?? ''
  internalEditing.value = false
  emit('edit-state-change', false)
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
    e.preventDefault()
    handleSave()
  }
  if (e.key === 'Escape') handleCancel()
}

// Register save/cancel for parent toolbar
onMounted(() => {
  if (isEditing.value) {
    emit('register-actions', {
      save: handleSave,
      cancel: handleCancel,
    })
  }
})

watch(() => isEditing.value, (val) => {
  if (val) {
    emit('register-actions', {
      save: handleSave,
      cancel: handleCancel,
    })
  } else {
    emit('register-actions', null)
  }
}, { flush: 'sync' })
</script>

<style scoped>
.action-block {
  position: relative;
  padding: 6px 8px;
  margin: 0 -8px;
  border-radius: 8px;
  transition: background 0.2s;
}

.action-block:hover {
  background: rgba(255, 255, 255, 0.02);
}

.action-block--editing {
  background: rgba(61, 184, 176, 0.03);
}

/* View Mode */
.action-view {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  font-size: 14px;
  line-height: 1.6;
}

.action-type-tag {
  display: inline-flex;
  align-items: center;
  font-size: 10px;
  font-weight: 500;
  color: var(--text-muted);
  background: rgba(255, 255, 255, 0.05);
  padding: 0px 6px;
  border-radius: 4px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  flex-shrink: 0;
}

.action-desc {
  color: var(--text-secondary);
  font-style: italic;
  flex: 1;
  min-width: 0;
}

.action-duration {
  font-size: 10px;
  color: var(--text-muted);
  opacity: 0.5;
  flex-shrink: 0;
}

/* Edit Mode */
.action-edit {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.edit-header {
  display: flex;
  align-items: center;
  gap: 8px;
}

.edit-indicator {
  font-size: 12px;
  color: var(--teal-primary);
  opacity: 0.6;
}

.edit-textarea {
  width: 100%;
  min-height: 60px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(61, 184, 176, 0.2);
  border-radius: 8px;
  padding: 8px 12px;
  font-size: 14px;
  color: var(--text-primary);
  resize: vertical;
  outline: none;
  transition: border-color 0.2s;
}

.edit-textarea:focus {
  border-color: rgba(61, 184, 176, 0.4);
}

.edit-footer {
  display: flex;
  align-items: center;
  gap: 12px;
}

.duration-field {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: var(--text-muted);
}

.duration-input {
  width: 72px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 4px;
  padding: 2px 8px;
  font-size: 12px;
  outline: none;
}

.duration-input:focus {
  border-color: rgba(61, 184, 176, 0.3);
}

.flex-1 {
  flex: 1;
}

.btn-cancel,
.btn-save {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-cancel {
  color: var(--text-muted);
}

.btn-cancel:hover {
  color: var(--text-primary);
  background: rgba(255, 255, 255, 0.06);
}

.btn-save {
  color: var(--teal-primary);
  background: var(--teal-surface);
}

.btn-save:hover {
  background: var(--teal-surface-hover);
}

.shortcut-hint {
  font-size: 10px;
  color: var(--text-muted);
  opacity: 0.4;
}
</style>

// frontend/src/components/script/ActionBlock.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { useScriptStore } from '@/stores/script-store';
import { cn } from '@/lib/utils';
import { Check, X } from 'lucide-react';
import { toast } from '@/stores/toast-store';
import type { Action } from '@/types/script';

interface ActionBlockProps {
  action: Action;
  /** External edit control — when true, enter edit mode */
  editing?: boolean;
  /** Called when edit mode changes (save/cancel) */
  onEditStateChange?: (editing: boolean) => void;
  /** Register save/cancel callbacks so parent toolbar can trigger them */
  registerActions?: (actions: { save: () => void; cancel: () => void } | null) => void;
  /** Hide internal save/cancel buttons (when parent toolbar provides them) */
  hideActions?: boolean;
}

const actionTypeLabel = (type: string): string => {
  const labels: Record<string, string> = {
    ACTION: '动作',
    REACTION: '反应',
    BEAT: '节拍',
    BUSINESS: '调度',
  };
  return labels[type] ?? type;
};

export function ActionBlock({ action, editing: externalEditing, onEditStateChange, registerActions, hideActions }: ActionBlockProps) {
  const script = useScriptStore((s) => s.script);
  const updateScene = useScriptStore((s) => s.updateScene);

  const [internalEditing, setInternalEditing] = useState(false);
  const [description, setDescription] = useState(action.description);
  const [durationMs, setDurationMs] = useState(action.durationMs?.toString() ?? '');
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const isEditing = externalEditing !== undefined ? externalEditing : internalEditing;

  // Sync external editing state
  useEffect(() => {
    if (externalEditing) {
      setDescription(action.description);
      setDurationMs(action.durationMs?.toString() ?? '');
    }
  }, [externalEditing, action.description, action.durationMs]);

  // Focus textarea when entering edit mode
  useEffect(() => {
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus();
      textareaRef.current.select();
    }
  }, [isEditing]);

  // Register save/cancel actions for parent toolbar
  useEffect(() => {
    if (isEditing && registerActions) {
      registerActions({ save: handleSave, cancel: handleCancel });
    } else if (!isEditing && registerActions) {
      registerActions(null);
    }
    return () => { registerActions?.(null); };
  }, [isEditing]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleSave = () => {
    const trimmed = description.trim();
    if (!trimmed) {
      toast.warning('请填写动作内容');
      return;
    }

    const scene = script?.scenes.find((s) => s.id === action.sceneId);
    if (!scene) return;

    const updatedActions = scene.actions.map((a) =>
      a.id === action.id
        ? {
            ...a,
            description: trimmed,
            durationMs: durationMs ? parseInt(durationMs, 10) || undefined : undefined,
          }
        : a
    );
    updateScene(action.sceneId, {
      actions: updatedActions as unknown as typeof scene.actions,
    } as Partial<typeof scene>);

    setInternalEditing(false);
    onEditStateChange?.(false);
    toast.success('💾 段落已更新');
  };

  const handleCancel = () => {
    setDescription(action.description);
    setDurationMs(action.durationMs?.toString() ?? '');
    setInternalEditing(false);
    onEditStateChange?.(false);
  };

  return (
    <div
      className={cn(
        'group/action relative text-sm py-1.5 px-2 -mx-2 rounded-lg transition-colors',
        'hover:bg-white/[0.02]'
      )}
    >
      {isEditing ? (
        /* ── Edit Mode ── */
        <div className="space-y-2">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1 text-[10px] font-medium text-muted-foreground/70 bg-white/5 rounded px-1.5 py-0.5 uppercase tracking-wider">
              {actionTypeLabel(action.actionType)}
            </span>
            <span className="text-teal-400/60">编辑模式</span>
          </div>

          <textarea
            ref={textareaRef}
            className="w-full bg-white/10 border border-teal-500/30 rounded-lg px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-teal-500/50 resize-y min-h-[60px]"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={3}
            placeholder="输入动作描述..."
            onKeyDown={(e) => {
              if ((e.key === 'Enter' && (e.ctrlKey || e.metaKey))) {
                e.preventDefault();
                handleSave();
              }
              if (e.key === 'Escape') handleCancel();
            }}
          />

          {!hideActions && (
            <>
              <div className="flex items-center gap-3">
                <label className="flex items-center gap-1.5 text-xs text-muted-foreground">
                  <span>时长 (ms)</span>
                  <input
                    className="w-20 bg-white/5 border border-white/10 rounded px-2 py-0.5 text-xs text-foreground focus:outline-none focus:border-teal-500/40"
                    value={durationMs}
                    onChange={(e) => setDurationMs(e.target.value)}
                    placeholder="auto"
                  />
                </label>
                <span className="flex-1" />
                <button
                  onClick={handleCancel}
                  className="flex items-center gap-1 px-2.5 py-1 text-xs rounded-md hover:bg-white/10 text-muted-foreground transition-colors"
                >
                  <X className="h-3 w-3" />
                  取消
                </button>
                <button
                  onClick={handleSave}
                  className="flex items-center gap-1 px-2.5 py-1 text-xs rounded-md bg-teal-500/20 text-teal-300 hover:bg-teal-500/30 transition-colors"
                >
                  <Check className="h-3 w-3" />
                  保存
                </button>
              </div>
              <p className="text-[10px] text-muted-foreground/40">
                Ctrl+Enter 保存 · Esc 取消
              </p>
            </>
          )}
        </div>
      ) : (
        /* ── View Mode ── */
        <div className="flex items-start gap-2">
          {/* Action type tag */}
          <span className="inline-flex items-center text-[10px] font-medium text-muted-foreground/70 bg-white/5 rounded px-1.5 py-0.5 shrink-0 uppercase tracking-wider select-none">
            {actionTypeLabel(action.actionType)}
          </span>

          <span className="text-muted-foreground/70 italic flex-1">
            {action.description}
          </span>

          {/* Duration indicator */}
          {action.durationMs && (
            <span className="text-[10px] text-muted-foreground/40 shrink-0">
              ~{(action.durationMs / 1000).toFixed(1)}s
            </span>
          )}
        </div>
      )}
    </div>
  );
}
