// frontend-vue/src/components/script/DialogueBlock.vue
<template>
  <div class="dialogue-block" :class="{ 'dialogue-block--editing': isEditing }">
    <!-- Edit Mode -->
    <div v-if="isEditing" class="dialogue-edit">
      <span class="edit-label">编辑对白</span>

      <div class="edit-row">
        <label class="field-label">
          <span>角色名</span>
          <input
            ref="inputRef"
            class="field-input name-input"
            v-model="localSpeaker"
            placeholder="角色名"
            maxlength="4"
          />
        </label>
        <label class="field-label">
          <span>情绪</span>
          <select class="field-select" v-model="localEmotion">
            <option v-for="em in EMOTIONS" :key="em" :value="em">
              {{ emotionLabel(em) }}
            </option>
          </select>
        </label>
      </div>

      <div class="edit-row">
        <label class="field-label flex-1">
          <span>提示</span>
          <input
            class="field-input"
            v-model="localParenthetical"
            placeholder="(可选) 如：低声、激动地..."
          />
        </label>
      </div>

      <textarea
        ref="textareaRef"
        class="edit-textarea"
        v-model="localContent"
        rows="2"
        placeholder="输入对白内容..."
        @keydown="handleKeydown"
      ></textarea>

      <!-- Actions -->
      <div class="edit-footer">
        <button class="btn-delete" @click="handleDelete">🗑 删除</button>
        <span class="flex-1"></span>
        <button class="btn-cancel" @click="handleCancel">取消</button>
        <button class="btn-save" @click="handleSave">保存</button>
      </div>
    </div>

    <!-- View Mode -->
    <div v-else class="dialogue-view">
      <span class="speaker">{{ dialogue.speaker }}</span>
      <span v-if="dialogue.emotion" class="emotion">({{ emotionLabel(dialogue.emotion) }})</span>
      <span v-if="dialogue.parenthetical" class="parenthetical">{{ dialogue.parenthetical }}</span>
      <span class="content">{{ dialogue.content }}</span>
      <span v-if="dialogue.replyTo" class="reply-indicator">↳ 回复 #{{ dialogue.replyTo }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, useTemplateRef, onMounted } from 'vue'
import { useScriptStore } from '@/stores/script'
import { emotionLabel } from '@/lib/utils'
import { toast } from '@/stores/toast'
import { deleteDialogueParagraph } from '@/lib/api'
import type { Dialogue } from '@/types/script'

const EMOTIONS = ['NEUTRAL', 'CALM', 'ANGRY', 'SAD', 'HAPPY', 'SURPRISED', 'FEARFUL'] as const

const props = defineProps<{
  dialogue: Dialogue
  editing?: boolean
  hideActions?: boolean
}>()

const emit = defineEmits<{
  'edit-state-change': [editing: boolean]
  'register-actions': [actions: { save: () => void; cancel: () => void } | null]
  'delete': [dialogueId: number]
}>()

const store = useScriptStore()
const internalEditing = ref(false)
const localSpeaker = ref(props.dialogue.speaker)
const localEmotion = ref(props.dialogue.emotion ?? 'NEUTRAL')
const localContent = ref(props.dialogue.content)
const localParenthetical = ref(props.dialogue.parenthetical ?? '')
const inputRef = useTemplateRef<HTMLInputElement>('inputRef')
const textareaRef = useTemplateRef<HTMLTextAreaElement>('textareaRef')

const isEditing = computed(() =>
  props.editing !== undefined ? props.editing : internalEditing.value
)

// Sync when entering edit mode + focus
watch(isEditing, (val) => {
  if (val) {
    localSpeaker.value = props.dialogue.speaker
    localEmotion.value = props.dialogue.emotion ?? 'NEUTRAL'
    localContent.value = props.dialogue.content
    localParenthetical.value = props.dialogue.parenthetical ?? ''
  }
  // Focus name input
  if (val) {
    setTimeout(() => {
      inputRef.value?.focus({ preventScroll: true })
    }, 50)
  }
})

function handleSave() {
  const trimmedSpeaker = localSpeaker.value.trim()
  const trimmedContent = localContent.value.trim()

  if (!trimmedSpeaker) {
    toast.warning('请填写角色名')
    return
  }
  if (trimmedSpeaker.length < 2 || trimmedSpeaker.length > 4) {
    toast.warning('角色名需为 2-4 个中文字符')
    return
  }
  if (!trimmedContent) {
    toast.warning('请填写对白内容')
    return
  }

  store.updateDialogue(props.dialogue.sceneId, props.dialogue.sequence, {
    speaker: trimmedSpeaker,
    emotion: localEmotion.value,
    content: trimmedContent,
    parenthetical: localParenthetical.value.trim() || undefined,
  })

  internalEditing.value = false
  emit('edit-state-change', false)
  toast.success('💾 段落已更新')
}

function handleCancel() {
  localSpeaker.value = props.dialogue.speaker
  localEmotion.value = props.dialogue.emotion ?? 'NEUTRAL'
  localContent.value = props.dialogue.content
  localParenthetical.value = props.dialogue.parenthetical ?? ''
  internalEditing.value = false
  emit('edit-state-change', false)
}

async function handleDelete() {
  if (!store.script?.id) {
    toast.warning('无法获取剧本信息，请刷新后重试')
    return
  }
  try {
    await deleteDialogueParagraph(store.script.id, props.dialogue.sceneId, props.dialogue.id!)
    emit('delete', props.dialogue.id!)
    internalEditing.value = false
    emit('edit-state-change', false)
    toast.success('段落已删除')
  } catch {
    toast.error('删除失败，请重试')
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
    e.preventDefault()
    handleSave()
  }
  if (e.key === 'Escape') handleCancel()
}

// Register save/cancel for parent toolbar
onMounted(() => {
  if (isEditing.value) {
    emit('register-actions', {
      save: handleSave,
      cancel: handleCancel,
    })
  }
})

watch(() => isEditing.value, (val) => {
  if (val) {
    emit('register-actions', {
      save: handleSave,
      cancel: handleCancel,
    })
  } else {
    emit('register-actions', null)
  }
}, { flush: 'sync' })
</script>

<style scoped>
.dialogue-block {
  position: relative;
  padding: 6px 8px;
  margin: 0 -8px;
  border-radius: 8px;
  transition: background 0.2s;
}

.dialogue-block:hover {
  background: rgba(255, 255, 255, 0.03);
}

.dialogue-block--editing {
  background: rgba(61, 184, 176, 0.03);
}

/* View Mode */
.dialogue-view {
  display: flex;
  align-items: baseline;
  gap: 4px;
  flex-wrap: wrap;
  font-size: 14px;
  line-height: 1.6;
}

.speaker {
  font-weight: 600;
  color: var(--teal-primary);
  flex-shrink: 0;
}

.emotion,
.parenthetical {
  font-size: 11px;
  color: var(--text-muted);
  flex-shrink: 0;
  opacity: 0.7;
}

.parenthetical {
  font-style: italic;
}

.content {
  color: var(--text-primary);
  opacity: 0.9;
  min-width: 0;
}

.reply-indicator {
  font-size: 10px;
  color: var(--text-muted);
  font-style: italic;
  opacity: 0.4;
  flex-shrink: 0;
}

/* Edit Mode */
.dialogue-edit {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.edit-label {
  font-size: 12px;
  color: var(--teal-primary);
  opacity: 0.6;
}

.edit-row {
  display: flex;
  align-items: center;
  gap: 12px;
}

.field-label {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: var(--text-muted);
}

.field-label span {
  flex-shrink: 0;
}

.field-input {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 6px;
  padding: 6px 10px;
  font-size: 14px;
  color: var(--text-primary);
  outline: none;
  transition: border-color 0.2s;
}

.field-input:focus {
  border-color: rgba(61, 184, 176, 0.3);
}

.name-input {
  width: 96px;
}

.field-select {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 6px;
  padding: 6px 8px;
  font-size: 14px;
  color: var(--text-primary);
  outline: none;
}

.field-select:focus {
  border-color: rgba(61, 184, 176, 0.3);
}

.field-select option {
  background: var(--ink-deep-elevated);
  color: var(--text-primary);
}

.flex-1 {
  flex: 1;
}

.edit-textarea {
  width: 100%;
  min-height: 50px;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(61, 184, 176, 0.2);
  border-radius: 8px;
  padding: 8px 12px;
  font-size: 14px;
  color: var(--text-primary);
  resize: vertical;
  outline: none;
  transition: border-color 0.2s;
}

.edit-textarea:focus {
  border-color: rgba(61, 184, 176, 0.4);
}

.edit-footer {
  display: flex;
  align-items: center;
  gap: 8px;
  justify-content: flex-end;
}

.btn-cancel,
.btn-save,
.btn-delete {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-delete {
  color: var(--cinnabar);
}

.btn-delete:hover {
  background: var(--cinnabar-surface);
}

.btn-cancel {
  color: var(--text-muted);
}

.btn-cancel:hover {
  color: var(--text-primary);
  background: rgba(255, 255, 255, 0.06);
}

.btn-save {
  color: var(--teal-primary);
  background: var(--teal-surface);
}

.btn-save:hover {
  background: var(--teal-surface-hover);
}

.shortcut-hint {
  font-size: 10px;
  color: var(--text-muted);
  opacity: 0.4;
}
</style>

// frontend/src/components/script/DialogueBlock.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { useScriptStore } from '@/stores/script-store';
import { emotionLabel, cn } from '@/lib/utils';
import { Check, X } from 'lucide-react';
import { toast } from '@/stores/toast-store';
import type { Dialogue } from '@/types/script';

interface DialogueBlockProps {
  dialogue: Dialogue;
  /** External edit control — when true, enter edit mode */
  editing?: boolean;
  /** Called when edit mode changes (save/cancel) */
  onEditStateChange?: (editing: boolean) => void;
  /** Register save/cancel callbacks so parent toolbar can trigger them */
  registerActions?: (actions: { save: () => void; cancel: () => void } | null) => void;
  /** Hide internal save/cancel buttons (when parent toolbar provides them) */
  hideActions?: boolean;
}

const EMOTIONS = [
  'NEUTRAL',
  'CALM',
  'ANGRY',
  'SAD',
  'HAPPY',
  'SURPRISED',
  'FEARFUL',
] as const;

export function DialogueBlock({
  dialogue,
  editing: externalEditing,
  onEditStateChange,
  registerActions,
  hideActions,
}: DialogueBlockProps) {
  const script = useScriptStore((s) => s.script);
  const updateDialogueStore = useScriptStore((s) => s.updateDialogue);

  const [internalEditing, setInternalEditing] = useState(false);
  const [speaker, setSpeaker] = useState(dialogue.speaker);
  const [emotion, setEmotion] = useState(dialogue.emotion ?? 'NEUTRAL');
  const [content, setContent] = useState(dialogue.content);
  const [parenthetical, setParenthetical] = useState(dialogue.parenthetical ?? '');
  const inputRef = useRef<HTMLInputElement>(null);

  const isEditing = externalEditing !== undefined ? externalEditing : internalEditing;

  // Sync external editing state
  useEffect(() => {
    if (externalEditing) {
      setSpeaker(dialogue.speaker);
      setEmotion(dialogue.emotion ?? 'NEUTRAL');
      setContent(dialogue.content);
      setParenthetical(dialogue.parenthetical ?? '');
    }
  }, [externalEditing, dialogue.speaker, dialogue.emotion, dialogue.content, dialogue.parenthetical]);

  // Focus content input when entering edit mode
  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isEditing]);

  // Register save/cancel actions for parent toolbar
  useEffect(() => {
    if (isEditing && registerActions) {
      registerActions({ save: handleSave, cancel: handleCancel });
    } else if (!isEditing && registerActions) {
      registerActions(null);
    }
    return () => { registerActions?.(null); };
  }, [isEditing]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleSave = () => {
    const trimmedSpeaker = speaker.trim();
    const trimmedContent = content.trim();

    if (!trimmedSpeaker) {
      toast.warning('请填写角色名');
      return;
    }
    if (trimmedSpeaker.length < 2 || trimmedSpeaker.length > 4) {
      toast.warning('角色名需为 2-4 个中文字符');
      return;
    }
    if (!trimmedContent) {
      toast.warning('请填写对白内容');
      return;
    }

    updateDialogueStore(dialogue.id, {
      speaker: trimmedSpeaker,
      emotion: emotion,
      content: trimmedContent,
      parenthetical: parenthetical.trim() || undefined,
    });

    setInternalEditing(false);
    onEditStateChange?.(false);
    toast.success('💾 段落已更新');
  };

  const handleCancel = () => {
    setSpeaker(dialogue.speaker);
    setEmotion(dialogue.emotion ?? 'NEUTRAL');
    setContent(dialogue.content);
    setParenthetical(dialogue.parenthetical ?? '');
    setInternalEditing(false);
    onEditStateChange?.(false);
  };

  return (
    <div
      className={cn(
        'group/dialogue relative text-sm leading-relaxed py-1.5 px-2 -mx-2 rounded-lg transition-colors',
        'hover:bg-white/[0.03]'
      )}
    >
      {isEditing ? (
        /* ── Edit Mode ── */
        <div className="space-y-2">
          <span className="text-xs text-teal-400/60">编辑对白</span>

          {/* Row 1: Character name + Emotion */}
          <div className="flex items-center gap-3">
            <label className="flex items-center gap-1.5 text-xs text-muted-foreground shrink-0">
              <span>角色名</span>
              <input
                className="w-24 bg-white/10 border border-white/10 rounded-md px-2.5 py-1.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-teal-500/40"
                value={speaker}
                onChange={(e) => setSpeaker(e.target.value)}
                placeholder="角色名"
                maxLength={4}
              />
            </label>

            <label className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <span>情绪</span>
              <select
                className="bg-white/10 border border-white/10 rounded-md px-2 py-1.5 text-sm text-foreground focus:outline-none focus:border-teal-500/40"
                value={emotion}
                onChange={(e) => setEmotion(e.target.value)}
              >
                {EMOTIONS.map((em) => (
                  <option key={em} value={em} className="bg-zinc-900">
                    {emotionLabel(em)}
                  </option>
                ))}
              </select>
            </label>

            <span className="flex-1" />
          </div>

          {/* Parenthetical */}
          <div>
            <label className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <span>提示</span>
              <input
                className="flex-1 bg-white/10 border border-white/10 rounded-md px-2.5 py-1.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-teal-500/40"
                value={parenthetical}
                onChange={(e) => setParenthetical(e.target.value)}
                placeholder="(可选) 如：低声、激动地..."
              />
            </label>
          </div>

          {/* Content */}
          <div>
            <textarea
              ref={inputRef as unknown as React.RefObject<HTMLTextAreaElement>}
              className="w-full bg-white/10 border border-teal-500/30 rounded-lg px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-teal-500/50 resize-y min-h-[50px]"
              value={content}
              onChange={(e) => setContent(e.target.value)}
              rows={2}
              placeholder="输入对白内容..."
              onKeyDown={(e) => {
                if ((e.key === 'Enter' && (e.ctrlKey || e.metaKey))) {
                  e.preventDefault();
                  handleSave();
                }
                if (e.key === 'Escape') handleCancel();
              }}
            />
          </div>

          {/* Action buttons — hidden when parent toolbar provides them */}
          {!hideActions && (
            <>
              <div className="flex items-center justify-end gap-2">
                <button
                  onClick={handleCancel}
                  className="flex items-center gap-1 px-2.5 py-1 text-xs rounded-md hover:bg-white/10 text-muted-foreground transition-colors"
                >
                  <X className="h-3 w-3" />
                  取消
                </button>
                <button
                  onClick={handleSave}
                  className="flex items-center gap-1 px-2.5 py-1 text-xs rounded-md bg-teal-500/20 text-teal-300 hover:bg-teal-500/30 transition-colors"
                >
                  <Check className="h-3 w-3" />
                  保存
                </button>
              </div>
              <p className="text-[10px] text-muted-foreground/40">
                Ctrl+Enter 保存 · Esc 取消
              </p>
            </>
          )}
        </div>
      ) : (
        /* ── View Mode ── */
        <div className="flex items-baseline gap-x-2 gap-y-0.5 flex-wrap">
          {/* Speaker */}
          <span className="font-semibold text-teal-400 shrink-0 select-none">
            {dialogue.speaker}
          </span>

          {/* Emotion badge */}
          {dialogue.emotion && (
            <span className="text-muted-foreground/70 text-[11px] shrink-0 select-none">
              ({emotionLabel(dialogue.emotion)})
            </span>
          )}

          {/* Parenthetical */}
          {dialogue.parenthetical && (
            <span className="text-muted-foreground/50 text-[11px] shrink-0 italic">
              {dialogue.parenthetical}
            </span>
          )}

          {/* Content */}
          <span className="text-foreground/90 min-w-0">{dialogue.content}</span>

          {/* Reply indicator */}
          {dialogue.replyTo && (
            <span className="text-[10px] text-muted-foreground/40 italic shrink-0">
              ↳ 回复 #{dialogue.replyTo}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
