// frontend-vue/src/components/script/ScriptEditor.vue
<template>
  <div class="editor-layout">
    <!-- Left sidebar: Scene list -->
    <aside class="editor-sidebar" :class="{ 'sidebar-hidden': !leftOpen }">
      <SceneList :scenes="scenes" />
    </aside>

    <!-- Center: Script content -->
    <main class="editor-main" ref="mainRef">
      <!-- Top bar -->
      <div class="editor-toolbar">
        <div class="toolbar-left">
          <button class="toolbar-icon-btn" @click="leftOpen = !leftOpen" title="切换场景列表">
            ◀
          </button>
          <span class="script-title">{{ script?.title ?? '剧本' }}</span>
        </div>

        <!-- Mode toggle -->
        <div class="mode-toggle">
          <button
            class="mode-btn"
            :class="{ 'mode-btn--active': !editMode }"
            @click="editMode = false"
          >📖 阅读</button>
          <button
            class="mode-btn"
            :class="{ 'mode-btn--active': editMode }"
            @click="editMode = true"
          >✏️ 编辑</button>
        </div>

        <button class="toolbar-icon-btn" @click="rightOpen = !rightOpen" title="切换角色面板">
          ▶
        </button>
      </div>

      <div class="script-scroll">
        <!-- Insertions before first scene (position 0) -->
        <div
          v-for="ins in insertionsAtStart"
          :key="'ins-' + ins.id"
          class="plot-insertion"
        >
          <div class="insertion-header">
            <span class="insertion-label">📝 情节插入</span>
            <button class="insertion-delete" @click="$emit('delete-insertion', ins.id)">✕</button>
          </div>
          <p class="insertion-text">{{ ins.text }}</p>
        </div>

        <!-- Scene cards -->
        <div
          v-for="(scene, idx) in scenes"
          :key="scene.id"
          :ref="(el) => setSceneRef(scene.id, el)"
        >
          <SceneCard
            :scene="scene"
            :selected="selectedSceneId === scene.id"
            :editable="editMode"
          />
          <!-- Insertions after this scene -->
          <div
            v-for="ins in getInsertionsAfter(idx)"
            :key="'ins-' + ins.id"
            class="plot-insertion"
          >
            <div class="insertion-header">
              <span class="insertion-label">📝 情节插入</span>
              <button class="insertion-delete" @click="$emit('delete-insertion', ins.id)">✕</button>
            </div>
            <p class="insertion-text">{{ ins.text }}</p>
          </div>
        </div>

        <!-- Empty state -->
        <div v-if="scenes.length === 0" class="empty-state">
          <div class="loading-spinner"></div>
          <p>暂无场景，请等待 AI 生成完成</p>
        </div>
      </div>
    </main>

    <!-- Right sidebar: Character panel -->
    <aside class="editor-sidebar editor-sidebar--right" :class="{ 'sidebar-hidden': !rightOpen }">
      <CharacterPanel
        :characters="script?.characters ?? []"
        :selected-scene="selectedScene"
      />
    </aside>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch, nextTick } from 'vue'
import { useScriptStore } from '@/stores/script'
import SceneList from './SceneList.vue'
import SceneCard from './SceneCard.vue'
import CharacterPanel from './CharacterPanel.vue'
import type { PlotInsertion } from '@/types/script'

const store = useScriptStore()

const leftOpen = ref(true)
const rightOpen = ref(true)
const editMode = ref(false)
const mainRef = ref<HTMLElement | null>(null)
const sceneRefs = new Map<number, HTMLElement>()
const hasScrolled = ref(false)

function setSceneRef(id: number, el: unknown) {
  if (el instanceof HTMLElement) {
    sceneRefs.set(id, el)
  } else {
    sceneRefs.delete(id)
  }
}

const script = computed(() => store.script)
const scenes = computed(() => store.script?.scenes ?? [])
const selectedSceneId = computed(() => store.selectedSceneId)
const selectedScene = computed(() => store.selectedScene)

const insertions = computed(() => store.script?.plotInsertions ?? [])

const insertionsAtStart = computed(() =>
  insertions.value.filter((ins) => ins.position === 0)
)

function getInsertionsAfter(idx: number): PlotInsertion[] {
  return insertions.value.filter((ins) => ins.position === idx + 1)
}

// Scroll to selected scene on mount
onMounted(() => {
  setTimeout(() => {
    if (store.selectedSceneId) {
      const el = sceneRefs.get(store.selectedSceneId)
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'start' })
        hasScrolled.value = true
        return
      }
    }
    if (!hasScrolled.value && mainRef.value) {
      mainRef.value.scrollTop = 0
    }
  }, 100)
})

// Entering edit mode: default to first scene, scroll to top
watch(editMode, (val) => {
  if (val) {
    if (!store.selectedSceneId && scenes.value.length > 0) {
      store.selectScene(scenes.value[0].id)
    }
    nextTick(() => {
      if (mainRef.value) {
        mainRef.value.scrollTop = 0
      }
    })
  }
})

// Scroll to scene when selected from list
watch(() => store.selectedSceneId, (id) => {
  if (id != null) {
    nextTick(() => {
      const el = sceneRefs.get(id)
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'start' })
      }
    })
  }
})
</script>

<style scoped>
.editor-layout {
  display: flex;
  height: calc(100vh - var(--topbar-height));
}

.editor-sidebar {
  width: 260px;
  border-right: 1px solid rgba(255, 255, 255, 0.05);
  background: rgba(255, 255, 255, 0.02);
  overflow: hidden;
  transition: width 0.3s;
  flex-shrink: 0;
}

.editor-sidebar--right {
  border-right: none;
  border-left: 1px solid rgba(255, 255, 255, 0.05);
}

.sidebar-hidden {
  width: 0;
  border: none;
}

.editor-main {
  flex: 1;
  overflow-y: auto;
}

.editor-toolbar {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 12px;
  background: rgba(15, 17, 21, 0.85);
  backdrop-filter: blur(12px);
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.toolbar-left {
  display: flex;
  align-items: center;
  gap: 8px;
}

.toolbar-icon-btn {
  padding: 4px 6px;
  border-radius: 6px;
  color: var(--text-muted);
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.toolbar-icon-btn:hover {
  color: var(--text-primary);
  background: rgba(255, 255, 255, 0.06);
}

.script-title {
  font-size: 12px;
  color: var(--text-muted);
  opacity: 0.5;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 160px;
}

/* Mode toggle */
.mode-toggle {
  display: flex;
  gap: 1px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 8px;
  padding: 2px;
  border: 1px solid rgba(255, 255, 255, 0.05);
}

.mode-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 12px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 500;
  color: var(--text-muted);
  cursor: pointer;
  transition: all 0.2s;
}

.mode-btn:hover {
  color: var(--text-primary);
}

.mode-btn--active {
  background: var(--teal-surface);
  color: var(--teal-primary);
  box-shadow: inset 0 1px 0 rgba(61, 184, 176, 0.08);
}

/* Script scroll area */
.script-scroll {
  max-width: 720px;
  margin: 0 auto;
  padding: 24px 16px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Plot Insertions */
.plot-insertion {
  border-radius: 10px;
  border: 1px dashed rgba(212, 168, 83, 0.2);
  background: rgba(212, 168, 83, 0.03);
  padding: 12px 16px;
  position: relative;
}

.plot-insertion:hover .insertion-delete {
  opacity: 1;
}

.insertion-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}

.insertion-label {
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: rgba(212, 168, 83, 0.5);
  font-weight: 500;
}

.insertion-delete {
  padding: 2px;
  border-radius: 4px;
  color: var(--text-muted);
  font-size: 14px;
  cursor: pointer;
  opacity: 0;
  transition: all 0.2s;
}

.insertion-delete:hover {
  color: var(--cinnabar);
  background: rgba(194, 59, 34, 0.1);
}

.insertion-text {
  font-size: 13px;
  color: var(--text-secondary);
  line-height: 1.6;
  white-space: pre-wrap;
}

/* Empty state */
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  padding: 64px 0;
  color: var(--text-muted);
  font-size: 14px;
}

.loading-spinner {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  border: 2px solid rgba(61, 184, 176, 0.2);
  border-top-color: var(--teal-primary);
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}
</style>

// frontend/src/components/script/ScriptEditor.tsx
'use client';

import { useScriptStore } from '@/stores/script-store';
import { cn } from '@/lib/utils';
import { SceneList } from './SceneList';
import { SceneCard } from './SceneCard';
import { CharacterPanel } from './CharacterPanel';
import { PanelLeft, PanelRight, BookOpen, Edit3, X } from 'lucide-react';
import { useState, useRef, useEffect, useCallback } from 'react';
import { ToastContainer } from '@/components/ui/toast';
import type { PlotInsertion } from '@/types/script';

interface ScriptEditorProps {
  scriptId: number;
}

/** Inline plot insertion block (user-added narrative between scenes) */
function PlotInsertionBlock({
  insertion,
  onDelete,
}: {
  insertion: PlotInsertion;
  onDelete: (id: number) => void;
}) {
  return (
    <div className="relative rounded-lg border border-dashed border-amber-500/30 bg-amber-500/[0.03] px-4 py-3 my-3 group/insertion">
      <button
        onClick={() => onDelete(insertion.id)}
        className="absolute top-2 right-2 p-0.5 rounded opacity-0 group-hover/insertion:opacity-100 hover:bg-white/10 text-muted-foreground hover:text-red-400 transition-all"
        title="删除此插入"
      >
        <X className="h-3.5 w-3.5" />
      </button>
      <div className="flex items-center gap-2 mb-1">
        <span className="text-[10px] uppercase tracking-wider text-amber-500/60 font-medium">
          📝 情节插入
        </span>
      </div>
      <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
        {insertion.text}
      </p>
    </div>
  );
}

export function ScriptEditor({ scriptId: _scriptId }: ScriptEditorProps) {
  const { script, selectedSceneId, setScript } = useScriptStore();
  const [leftOpen, setLeftOpen] = useState(true);
  const [rightOpen, setRightOpen] = useState(true);
  const [editMode, setEditMode] = useState(false);
  const sceneRefs = useRef<Map<number, HTMLDivElement>>(new Map());
  const mainRef = useRef<HTMLElement>(null);
  const hasScrolledRef = useRef(false);

  const selectedScene = script?.scenes.find((s) => s.id === selectedSceneId);

  // Scroll to selected scene on mount / when selection changes
  useEffect(() => {
    // Small delay to ensure DOM is rendered
    const timer = setTimeout(() => {
      if (selectedSceneId) {
        const el = sceneRefs.current.get(selectedSceneId);
        if (el) {
          el.scrollIntoView({ behavior: 'smooth', block: 'start' });
          hasScrolledRef.current = true;
          return;
        }
      }
      // No scene selected or element not found — scroll to top
      if (!hasScrolledRef.current && mainRef.current) {
        mainRef.current.scrollTop = 0;
      }
    }, 100);
    return () => clearTimeout(timer);
  }, [selectedSceneId]);

  const insertions = script?.plotInsertions ?? [];
  const scenes = script?.scenes ?? [];

  const handleDeleteInsertion = useCallback(
    async (insertionId: number) => {
      if (!script) return;
      try {
        await fetch(
          `${process.env.NEXT_PUBLIC_API_URL ?? ''}/api/v1/scripts/${script.id}/plot-insertions/${insertionId}`,
          { method: 'DELETE' }
        );
        const scriptRes = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL ?? ''}/api/v1/scripts/${script.id}`
        );
        if (scriptRes.ok) {
          const updated = await scriptRes.json();
          setScript(updated);
        }
      } catch (err) {
        console.error('Failed to delete plot insertion:', err);
      }
    },
    [script, setScript]
  );

  return (
    <div className="flex h-[calc(100vh-6rem)]">
      <ToastContainer />
      {/* Left sidebar: Scene list */}
      <aside
        className={`${
          leftOpen ? 'w-64' : 'w-0'
        } border-r border-white/5 bg-white/[0.02] overflow-hidden transition-all duration-300 shrink-0`}
      >
        <SceneList scenes={scenes} />
      </aside>

      {/* Center: Script content */}
      <main ref={mainRef} className="flex-1 overflow-y-auto">
        {/* Top bar: sidebar toggles + mode switch */}
        <div className="sticky top-0 z-10 flex items-center justify-between px-3 py-2 glass border-b border-white/5">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setLeftOpen(!leftOpen)}
              className="p-1.5 rounded-md hover:bg-white/10 text-muted-foreground hover:text-foreground transition-colors"
              title="切换场景列表"
            >
              <PanelLeft className="h-4 w-4" />
            </button>
            <span className="text-xs text-muted-foreground/40 font-medium hidden sm:inline">
              {script?.title ?? '剧本'}
            </span>
          </div>

          {/* Mode toggle */}
          <div className="flex items-center gap-1 bg-white/[0.03] rounded-lg p-0.5 border border-white/5">
            <button
              onClick={() => setEditMode(false)}
              className={cn(
                'flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-all duration-200',
                !editMode
                  ? 'bg-teal-500/20 text-teal-300 shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              )}
            >
              <BookOpen className="h-3.5 w-3.5" />
              阅读
            </button>
            <button
              onClick={() => setEditMode(true)}
              className={cn(
                'flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-all duration-200',
                editMode
                  ? 'bg-amber-500/20 text-amber-300 shadow-sm'
                  : 'text-muted-foreground hover:text-foreground'
              )}
            >
              <Edit3 className="h-3.5 w-3.5" />
              编辑
            </button>
          </div>

          <button
            onClick={() => setRightOpen(!rightOpen)}
            className="p-1.5 rounded-md hover:bg-white/10 text-muted-foreground hover:text-foreground transition-colors"
            title="切换角色面板"
          >
            <PanelRight className="h-4 w-4" />
          </button>
        </div>

        <div className="max-w-3xl mx-auto py-8 px-6 space-y-6">
          {/* Insertions before first scene (position 0) */}
          {insertions
            .filter((ins) => ins.position === 0)
            .map((ins) => (
              <PlotInsertionBlock
                key={`ins-${ins.id}`}
                insertion={ins}
                onDelete={handleDeleteInsertion}
              />
            ))}

          {scenes.map((scene, idx) => (
            <div
              key={scene.id}
              ref={(el) => {
                if (el) sceneRefs.current.set(scene.id, el);
                else sceneRefs.current.delete(scene.id);
              }}
            >
              <SceneCard
                scene={scene}
                selected={selectedSceneId === scene.id}
                editable={editMode}
              />
              {/* Insertions after this scene */}
              {insertions
                .filter((ins) => ins.position === idx + 1)
                .map((ins) => (
                  <PlotInsertionBlock
                    key={`ins-${ins.id}`}
                    insertion={ins}
                    onDelete={handleDeleteInsertion}
                  />
                ))}
            </div>
          ))}

          {scenes.length === 0 && (
            <div className="text-center py-16">
              <div className="inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-white/5 mb-4">
                <div className="h-8 w-8 rounded-full border-2 border-teal-500/30 border-t-teal-400 animate-spin" />
              </div>
              <p className="text-muted-foreground">暂无场景，请等待 AI 生成完成</p>
            </div>
          )}
        </div>
      </main>

      {/* Right sidebar: Character panel */}
      <aside
        className={`${
          rightOpen ? 'w-80' : 'w-0'
        } border-l border-white/5 bg-white/[0.02] overflow-hidden transition-all duration-300 shrink-0`}
      >
        <CharacterPanel
          characters={script?.characters ?? []}
          selectedScene={selectedScene ?? null}
        />
      </aside>
    </div>
  );
}
