// frontend/src/components/script/WorkflowProgress.tsx
'use client';

import { useScriptStore } from '@/stores/script-store';
import { Sparkles, CheckCircle2 } from 'lucide-react';

interface WorkflowProgressProps {
  progress: number;
}

export function WorkflowProgress({ progress }: WorkflowProgressProps) {
  const { script } = useScriptStore();
  const isActive = script?.status === 'GENERATING';
  const isComplete = progress >= 100;

  if (!isActive && isComplete) return null;

  return (
    <div className="glass border-b border-white/5 px-6 py-3">
      <div className="max-w-3xl mx-auto flex items-center gap-4">
        {/* Status icon */}
        <div
          className={`shrink-0 h-8 w-8 rounded-lg flex items-center justify-center ${
            isActive
              ? 'bg-teal-500/10 text-teal-400'
              : 'bg-teal-500/10 text-teal-400'
          }`}
        >
          {isActive ? (
            <Sparkles className="h-4 w-4 animate-pulse" />
          ) : (
            <CheckCircle2 className="h-4 w-4" />
          )}
        </div>

        {/* Progress bar */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between text-xs mb-1.5">
            <span className={`font-medium ${isActive ? 'text-teal-400' : 'text-muted-foreground'}`}>
              {isActive ? 'AI 正在生成...' : '生成完成'}
            </span>
            <span className="text-muted-foreground font-mono tabular-nums">
              {Math.round(progress)}%
            </span>
          </div>
          <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
            <div
              className="h-full rounded-full transition-all duration-700 ease-out"
              style={{
                width: `${progress}%`,
                background:
                  'linear-gradient(90deg, oklch(0.72 0.14 185), oklch(0.65 0.16 200))',
                boxShadow: isActive
                  ? '0 0 12px oklch(0.72 0.14 185 / 0.4)'
                  : 'none',
              }}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-vue/src/components/script/WorkflowProgress.vue
<template>
  <div class="workflow-bar" v-if="visible">
    <div class="bar-content">
      <span class="bar-icon">{{ isComplete ? '✅' : '✨' }}</span>
      <div class="bar-progress-wrap">
        <div class="bar-track">
          <div
            class="bar-fill"
            :class="{ 'bar-fill--complete': isComplete }"
            :style="{ width: progressPercent + '%' }"
          ></div>
        </div>
        <span class="bar-text">{{ statusText }}</span>
      </div>
      <span class="bar-pct">{{ Math.round(progressPercent) }}%</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  percent?: number
  message?: string
  visible?: boolean
}>()

const progressPercent = computed(() => props.percent ?? 0)
const isComplete = computed(() => progressPercent.value >= 100)
const statusText = computed(() => {
  if (props.message) return props.message
  if (isComplete.value) return '生成完成'
  return 'AI 正在生成剧本...'
})
</script>

<style scoped>
.workflow-bar {
  background: var(--glass-bg);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border-bottom: 1px solid var(--glass-border);
  padding: 8px 16px;
}

.bar-content {
  display: flex;
  align-items: center;
  gap: 12px;
  max-width: 56rem;
  margin: 0 auto;
}

.bar-icon {
  font-size: 16px;
  flex-shrink: 0;
}

.bar-progress-wrap {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}

.bar-track {
  height: 4px;
  border-radius: 2px;
  background: rgba(255, 255, 255, 0.08);
  overflow: hidden;
}

.bar-fill {
  height: 100%;
  border-radius: 2px;
  background: linear-gradient(90deg, var(--teal-primary), var(--teal-hover));
  transition: width 0.5s ease-out;
}

.bar-fill--complete {
  background: linear-gradient(90deg, var(--teal-muted), var(--teal-primary));
}

.bar-text {
  font-size: 11px;
  color: var(--text-muted);
}

.bar-pct {
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--teal-primary);
  font-weight: 600;
  flex-shrink: 0;
}
</style>
